#!/bin/bash

#Changes the repositories.
pve_ent=/etc/apt/sources.list.d/pve-enterprise.list
pve_ceph=/etc/apt/sources.list.d/ceph.list
pve_rep=/etc/apt/sources.list
pve_nosub=$(cat <<EOF
deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
EOF
)

sed -i 's/^deb/\#deb/' "$pve_ent" "$pve_ceph"

printf '%s\n' "$pve_nosub" >> "$pve_rep"

echo "Please enter the from email you would like proxmox to use. (e.g. apex@vulscan.com)"
read from_email

sed -i "1a email_from: $from_email" /etc/pve/datacenter.cfg

#This will remove LVM storage and make Local have the ability to store Disk Images
lvremove /dev/pve/data -y \
&& lvresize -l +100%FREE /dev/pve/root -y \
&& resize2fs /dev/mapper/pve-root -y

sed -i '/content/!b;/images/b;s/$/,images/' /etc/pve/storage.cfg
sed -i '/^lvmthin: local-lvm/,+3 d' /etc/pve/storage.cfg

#Install Fail2ban
wget -O fail2ban_install https://raw.githubusercontent.com/chuckmcilrath/scripts/refs/heads/main/fail2ban_install \
&& chmod +x fail2ban_install \
&& apt update \
&& ./fail2ban_install

#Update and upgrade as well as add the USB storage and start a restore.
apt upgrade -y && apt install ntfs-3g -y \
&& mkdir /mnt/usb-backup \
&& mount /dev/disk/by-id/usb-Seagate_One_Touch_Hub_00000000NAC92Y7J-0:0-part2 /mnt/usb-backup \
&& pvesm add dir USB-Backup --path /mnt/usb-backup --content backup,iso \
&& qmrestore /mnt/usb-backup/dump/vzdump-qemu-104-2025_02_11-16_11_43.vma.zst 104 \
&& qmrestore /mnt/usb-backup/dump/vzdump-qemu-105-2025_02_11-16_15_39.vma.zst 105
