#!/bin/bash

resolved_path=/etc/systemd/resolved.conf

while true; do
    # Input from user
    echo -e "Choose the install type: \n\n1. Wireguard Server \n2. Wireguard Client\nType \"exit\" to exit the script."
    read install_type

    case "$install_type" in
        1)
            echo -e "Starting the installation of the Wireguard server...\nStarting update and upgrade for this machine..."
            apt update &> /dev/null && apt upgrade -y &> /dev/null
            echo -e "apt update and apt upgrade have completed.\nLooking for systemd-resolved..."
            if ! dpkg -l | grep systemd-resolved &> /dev/null; then
                echo "systemd-resolved not found. Installing systemd-resolved..."
                apt install systemd-resolved -y &> /dev/null
                if dpkg -l | grep systemd-resolved &> /dev/null; then
                        echo "systemd-resolved has been successfully installed."
                    else
                        echo "Installation failed. Please clear the error and try again. Exiting Wireguard installation."
                        exit 1
                fi
            else
                echo "systemd-resolved is already installed. Continuing..."
            fi

            # Function to check if the entered IP is valid for the systemd-resolved configuration.
            is_valid_ip() {
                local ip=$1
                local IFS='.'
                local -a octets=($ip)

                [[ "${octets[0]}" -eq 127 ]] && return 1
                [[ ${#octets[@]} -ne 4 ]] && return 1

                # Check each octet is between 0 and 255
                for octet in "${octets[@]}"; do
                    [[ ! "$octet" =~ ^[0-9]+$ ]] && return 1
                    ((octet < 0 || octet > 255)) && return 1
                done

                return 0  # IP is valid
            }

            # Loop until valid input
            while true; do
                read -p "Enter a DNS for Resolved to use (input the gateway or firewall here): " ip
                if is_valid_ip "$ip"; then
                    echo "Valid IP address: $ip"
                    sed -i "/^#\?DNS=/c\DNS=$ip" "$resolved_path"
                    systemctl restart systemd-resolved.service
                        if ping -q -c 1 -w 1 &> /dev/null "$ip"; then
                            echo "ping to "$ip" was successful. Continuing with Installation..."
                            break #MIGHT NEED TO REMOVE!!!
                        else
                            echo "ping was unsuccessful, please try again."
                        fi
                else
                    echo "Invalid IP! Please enter a correct IP address (0.0.0.0 - 255.255.255.255)."
                fi
            done

            #Install iptables
            if ! dpkg -l | grep iptables &> /dev/null; then
                echo "iptables not found. Installing iptables..."
                apt install iptables -y &> /dev/null
                if dpkg -l | grep iptables &> /dev/null; then
                        echo "iptables has been successfully installed."
                    else
                        echo "Installation failed. Please clear the error and try again. Exiting Wireguard installation."
                        exit 1
                fi
            else
                echo "iptables is already installed. Continuing..."
            fi

            #Install ssh
            if ! dpkg -l | grep openssh &> /dev/null; then
                echo "Openssh not found. Installing openssh and it's dependencies..."
                apt install openssh-client -y &> /dev/null \ 
                && apt install openssh-server -y &> /dev/null \
                && apt install openssh-sftp-server -y &> /dev/null
                if dpkg -l | grep ssh &> /dev/null; then
                        echo "openssh and it's dependencies has been successfully installed."
                    else
                        echo "Installation failed. Please clear the error and try again. Exiting Wireguard installation."
                        exit 1
                fi
            else
                echo "Openssh is already installed. Continuing..."
            fi
            echo "The installation has been completed!"
            break # Exit the loop
            ;;
        exit)
            echo "The script will now exit."
            break
            ;;
        *)
            echo "Invalid Option."
            ;;
    esac
done
